### ISSUE TITLE
Change hard to read text color appearing in the "Ultimaker Dark" theme

### ISSUE THREAD

**Issue by faisal-bhuiyan** [tetonsim/is-cura-ui#447] opened 2021-02-15 19:37 UTC
_Preface: This is kind of nitpicky and not crucial for the upcoming release._

Some of the text in the SmartSlice tab with Cura UI in the "Ultimaker Dark" theme setting appear as too dark to read comfortably. Also the SmartSlice logo appears to be not optimized for this specific theme. We might want to rectify them for a more pleasing visual experience for the user. Please see the attached figure for details.

![dark_theme_text](https://user-images.githubusercontent.com/59463700/107986899-447aca80-6f8a-11eb-8720-6688ace32f16.png)

![dark_theme_text](https://user-images.githubusercontent.com/59463700/107987155-c23ed600-6f8a-11eb-8076-c031e2a7074a.png)

**Comment by dougkenik** [comment] 2021-02-15 19:39
Duplicate of #191

**Closed by dougkenik** 2021-02-15 19:39 UTC
